spring.application.name=product-app
server.port=8080
spring.datasource.url=jdbc:postgresql://db:5432/new_product_db
spring.datasource.username=user_product
spring.datasource.password=user_product@321
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
